// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const BookingCreateSchema = {
    properties: {
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        room_id: {
            type: 'string',
            format: 'uuid',
            title: 'Room Id'
        },
        check_in: {
            type: 'string',
            format: 'date-time',
            title: 'Check In'
        },
        check_out: {
            type: 'string',
            format: 'date-time',
            title: 'Check Out'
        },
        status: {
            '$ref': '#/components/schemas/BookingStatus',
            default: 'confirmed'
        },
        adults: {
            type: 'integer',
            maximum: 6,
            minimum: 1,
            title: 'Adults',
            default: 1
        },
        children: {
            type: 'integer',
            maximum: 4,
            minimum: 0,
            title: 'Children',
            default: 0
        },
        total_amount: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Total Amount'
        },
        paid_amount: {
            type: 'number',
            title: 'Paid Amount',
            default: 0
        },
        special_requests: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Special Requests'
        }
    },
    type: 'object',
    required: ['customer_id', 'room_id', 'check_in', 'check_out', 'total_amount'],
    title: 'BookingCreate'
} as const;

export const BookingPublicSchema = {
    properties: {
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        room_id: {
            type: 'string',
            format: 'uuid',
            title: 'Room Id'
        },
        check_in: {
            type: 'string',
            format: 'date-time',
            title: 'Check In'
        },
        check_out: {
            type: 'string',
            format: 'date-time',
            title: 'Check Out'
        },
        status: {
            '$ref': '#/components/schemas/BookingStatus',
            default: 'confirmed'
        },
        adults: {
            type: 'integer',
            maximum: 6,
            minimum: 1,
            title: 'Adults',
            default: 1
        },
        children: {
            type: 'integer',
            maximum: 4,
            minimum: 0,
            title: 'Children',
            default: 0
        },
        total_amount: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Total Amount'
        },
        paid_amount: {
            type: 'number',
            title: 'Paid Amount',
            default: 0
        },
        special_requests: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Special Requests'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        customer: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CustomerPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        room: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/RoomPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        booking_date: {
            type: 'string',
            format: 'date-time',
            title: 'Booking Date'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['customer_id', 'room_id', 'check_in', 'check_out', 'total_amount', 'id', 'booking_date', 'created_at'],
    title: 'BookingPublic'
} as const;

export const BookingStatusSchema = {
    type: 'string',
    enum: ['confirmed', 'checked_in', 'checked_out', 'cancelled'],
    title: 'BookingStatus'
} as const;

export const BookingUpdateSchema = {
    properties: {
        customer_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Id'
        },
        room_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Room Id'
        },
        check_in: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Check In'
        },
        check_out: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Check Out'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/BookingStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        adults: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Adults'
        },
        children: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Children'
        },
        total_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Amount'
        },
        paid_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Paid Amount'
        },
        special_requests: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Special Requests'
        }
    },
    type: 'object',
    title: 'BookingUpdate'
} as const;

export const BookingsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BookingPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'BookingsPublic'
} as const;

export const CustomerCreateSchema = {
    properties: {
        first_name: {
            type: 'string',
            maxLength: 100,
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            maxLength: 100,
            title: 'Last Name'
        },
        email: {
            type: 'string',
            maxLength: 255,
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        passport_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Passport Number'
        },
        nationality: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nationality'
        },
        date_of_birth: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Of Birth'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['first_name', 'last_name', 'email'],
    title: 'CustomerCreate'
} as const;

export const CustomerPublicSchema = {
    properties: {
        first_name: {
            type: 'string',
            maxLength: 100,
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            maxLength: 100,
            title: 'Last Name'
        },
        email: {
            type: 'string',
            maxLength: 255,
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        passport_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Passport Number'
        },
        nationality: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 100
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nationality'
        },
        date_of_birth: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Of Birth'
        },
        address: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        total_spent: {
            type: 'number',
            title: 'Total Spent'
        },
        total_bookings: {
            type: 'integer',
            title: 'Total Bookings'
        },
        first_booking_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Booking Date'
        },
        last_booking_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Booking Date'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['first_name', 'last_name', 'email', 'id', 'total_spent', 'total_bookings', 'first_booking_date', 'last_booking_date', 'created_at'],
    title: 'CustomerPublic'
} as const;

export const CustomerUpdateSchema = {
    properties: {
        first_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        passport_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Passport Number'
        },
        nationality: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nationality'
        },
        date_of_birth: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Of Birth'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        tags: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'CustomerUpdate'
} as const;

export const CustomersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CustomerPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CustomersPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['username', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RoomCreateSchema = {
    properties: {
        room_number: {
            type: 'string',
            maxLength: 10,
            title: 'Room Number'
        },
        floor: {
            type: 'integer',
            maximum: 20,
            minimum: 1,
            title: 'Floor'
        },
        room_type: {
            '$ref': '#/components/schemas/RoomType'
        },
        price_per_night: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Price Per Night'
        },
        status: {
            '$ref': '#/components/schemas/RoomStatus',
            default: 'available'
        },
        max_occupancy: {
            type: 'integer',
            maximum: 6,
            minimum: 1,
            title: 'Max Occupancy',
            default: 2
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['room_number', 'floor', 'room_type', 'price_per_night'],
    title: 'RoomCreate'
} as const;

export const RoomPublicSchema = {
    properties: {
        room_number: {
            type: 'string',
            maxLength: 10,
            title: 'Room Number'
        },
        floor: {
            type: 'integer',
            maximum: 20,
            minimum: 1,
            title: 'Floor'
        },
        room_type: {
            '$ref': '#/components/schemas/RoomType'
        },
        price_per_night: {
            type: 'number',
            exclusiveMinimum: 0,
            title: 'Price Per Night'
        },
        status: {
            '$ref': '#/components/schemas/RoomStatus',
            default: 'available'
        },
        max_occupancy: {
            type: 'integer',
            maximum: 6,
            minimum: 1,
            title: 'Max Occupancy',
            default: 2
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['room_number', 'floor', 'room_type', 'price_per_night', 'id', 'created_at'],
    title: 'RoomPublic'
} as const;

export const RoomStatusSchema = {
    type: 'string',
    enum: ['available', 'occupied', 'cleaning', 'maintenance'],
    title: 'RoomStatus'
} as const;

export const RoomTypeSchema = {
    type: 'string',
    enum: ['single', 'double', 'suite', 'deluxe', 'presidential'],
    title: 'RoomType'
} as const;

export const RoomUpdateSchema = {
    properties: {
        room_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Room Number'
        },
        floor: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Floor'
        },
        room_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/RoomType'
                },
                {
                    type: 'null'
                }
            ]
        },
        price_per_night: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Per Night'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/RoomStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        max_occupancy: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Max Occupancy'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'RoomUpdate'
} as const;

export const RoomsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RoomPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RoomsPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 3,
            title: 'Username'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 3,
            title: 'Username'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['username', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 3,
            title: 'Username'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;