// This file is auto-generated by @hey-api/openapi-ts

export const AuditLogPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        action: {
            type: 'string',
            title: 'Action'
        },
        entity_type: {
            type: 'string',
            title: 'Entity Type'
        },
        entity_id: {
            type: 'string',
            format: 'uuid',
            title: 'Entity Id'
        },
        entity_name: {
            type: 'string',
            title: 'Entity Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        old_values: {
            anyOf: [
                {
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Old Values'
        },
        new_values: {
            anyOf: [
                {
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'New Values'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            title: 'Timestamp'
        }
    },
    type: 'object',
    required: ['id', 'user_id', 'username', 'action', 'entity_type', 'entity_id', 'entity_name', 'description', 'old_values', 'new_values', 'timestamp'],
    title: 'AuditLogPublic'
} as const;

export const AuditLogsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/AuditLogPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'AuditLogsPublic'
} as const;

export const Body_files_upload_passportSchema = {
    properties: {
        file: {
            type: 'string',
            format: 'binary',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_files-upload_passport'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const BookingCreateSchema = {
    properties: {
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        room_id: {
            type: 'string',
            format: 'uuid',
            title: 'Room Id'
        },
        check_in: {
            type: 'string',
            format: 'date-time',
            title: 'Check In'
        },
        check_out: {
            type: 'string',
            format: 'date-time',
            title: 'Check Out'
        },
        status: {
            '$ref': '#/components/schemas/BookingStatus',
            default: 'confirmed'
        },
        total_amount: {
            type: 'number',
            maximum: 1000000,
            exclusiveMinimum: 0,
            title: 'Total Amount'
        },
        discount: {
            type: 'number',
            maximum: 100,
            minimum: 0,
            title: 'Discount',
            default: 0
        },
        discount_reason: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discount Reason'
        },
        payment_method: {
            '$ref': '#/components/schemas/PaymentMethod',
            default: 'cash'
        },
        registration_need: {
            type: 'boolean',
            title: 'Registration Need',
            default: true
        }
    },
    type: 'object',
    required: ['customer_id', 'room_id', 'check_in', 'check_out', 'total_amount'],
    title: 'BookingCreate'
} as const;

export const BookingPublicSchema = {
    properties: {
        customer_id: {
            type: 'string',
            format: 'uuid',
            title: 'Customer Id'
        },
        room_id: {
            type: 'string',
            format: 'uuid',
            title: 'Room Id'
        },
        check_in: {
            type: 'string',
            format: 'date-time',
            title: 'Check In'
        },
        check_out: {
            type: 'string',
            format: 'date-time',
            title: 'Check Out'
        },
        status: {
            '$ref': '#/components/schemas/BookingStatus',
            default: 'confirmed'
        },
        total_amount: {
            type: 'number',
            maximum: 1000000,
            exclusiveMinimum: 0,
            title: 'Total Amount'
        },
        discount: {
            type: 'number',
            maximum: 100,
            minimum: 0,
            title: 'Discount',
            default: 0
        },
        discount_reason: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discount Reason'
        },
        payment_method: {
            '$ref': '#/components/schemas/PaymentMethod',
            default: 'cash'
        },
        registration_need: {
            type: 'boolean',
            title: 'Registration Need',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        customer: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CustomerPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        room: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/RoomPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        booking_date: {
            type: 'string',
            format: 'date-time',
            title: 'Booking Date'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        actual_check_in: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actual Check In'
        },
        actual_check_out: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actual Check Out'
        },
        payment_adjustments: {
            items: {
                type: 'object'
            },
            type: 'array',
            title: 'Payment Adjustments'
        }
    },
    type: 'object',
    required: ['customer_id', 'room_id', 'check_in', 'check_out', 'total_amount', 'id', 'booking_date', 'created_at'],
    title: 'BookingPublic'
} as const;

export const BookingStatusSchema = {
    type: 'string',
    enum: ['confirmed', 'checked_in', 'checked_out', 'cancelled'],
    title: 'BookingStatus'
} as const;

export const BookingUpdateSchema = {
    properties: {
        customer_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Id'
        },
        room_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Room Id'
        },
        check_in: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Check In'
        },
        check_out: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Check Out'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/BookingStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        total_amount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Amount'
        },
        discount: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discount'
        },
        discount_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discount Reason'
        },
        payment_method: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PaymentMethod'
                },
                {
                    type: 'null'
                }
            ]
        },
        registration_need: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Need'
        },
        actual_check_in: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actual Check In'
        },
        actual_check_out: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Actual Check Out'
        },
        payment_adjustments: {
            anyOf: [
                {
                    items: {
                        type: 'object'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Payment Adjustments'
        }
    },
    type: 'object',
    title: 'BookingUpdate'
} as const;

export const BookingsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BookingPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'BookingsPublic'
} as const;

export const CustomerCreateSchema = {
    properties: {
        first_name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Last Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        date_of_birth: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Of Birth'
        },
        district: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/District'
                },
                {
                    type: 'null'
                }
            ]
        },
        passport_photo_path: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Passport Photo Path'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    required: ['first_name', 'last_name'],
    title: 'CustomerCreate'
} as const;

export const CustomerPublicSchema = {
    properties: {
        first_name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            maxLength: 100,
            minLength: 1,
            title: 'Last Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        date_of_birth: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Of Birth'
        },
        district: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/District'
                },
                {
                    type: 'null'
                }
            ]
        },
        passport_photo_path: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Passport Photo Path'
        },
        notes: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        total_spent: {
            type: 'number',
            title: 'Total Spent'
        },
        total_bookings: {
            type: 'integer',
            title: 'Total Bookings'
        },
        first_booking_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Booking Date'
        },
        last_booking_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Booking Date'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['first_name', 'last_name', 'id', 'total_spent', 'total_bookings', 'first_booking_date', 'last_booking_date', 'created_at'],
    title: 'CustomerPublic'
} as const;

export const CustomerUpdateSchema = {
    properties: {
        first_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        date_of_birth: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Of Birth'
        },
        district: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/District'
                },
                {
                    type: 'null'
                }
            ]
        },
        passport_photo_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Passport Photo Path'
        },
        tags: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        }
    },
    type: 'object',
    title: 'CustomerUpdate'
} as const;

export const CustomersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/CustomerPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'CustomersPublic'
} as const;

export const DateModificationRequestSchema = {
    properties: {
        new_check_in: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'New Check In'
        },
        new_check_out: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'New Check Out'
        }
    },
    type: 'object',
    title: 'DateModificationRequest',
    description: 'Request model for modifying booking dates.'
} as const;

export const DiscountModificationRequestSchema = {
    properties: {
        new_discount: {
            type: 'number',
            maximum: 100,
            minimum: 0,
            title: 'New Discount'
        },
        discount_reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discount Reason'
        }
    },
    type: 'object',
    required: ['new_discount'],
    title: 'DiscountModificationRequest',
    description: 'Request model for modifying booking discount with payment adjustment.'
} as const;

export const DistrictSchema = {
    type: 'string',
    enum: ['Almazar', 'Bektemir', 'Mirabad', 'Mirzo Ulugbek', 'Sergeli', 'Uchtepa', 'Chilanzar', 'Shaykhantakhur', 'Yunusabad', 'Yakkasaray', 'Yashnabad', 'Yangihayot'],
    title: 'District',
    description: 'Districts of Tashkent'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const PaymentAdjustmentResponseSchema = {
    properties: {
        booking: {
            '$ref': '#/components/schemas/BookingPublic'
        },
        payment_difference: {
            type: 'number',
            title: 'Payment Difference'
        }
    },
    type: 'object',
    required: ['booking', 'payment_difference'],
    title: 'PaymentAdjustmentResponse',
    description: 'Response model for operations that result in payment adjustments.'
} as const;

export const PaymentMethodSchema = {
    type: 'string',
    enum: ['cash', 'transfer', 'terminal'],
    title: 'PaymentMethod'
} as const;

export const RoomChangeRequestSchema = {
    properties: {
        new_room_id: {
            type: 'string',
            format: 'uuid',
            title: 'New Room Id'
        }
    },
    type: 'object',
    required: ['new_room_id'],
    title: 'RoomChangeRequest',
    description: 'Request model for changing booking room.'
} as const;

export const RoomCreateSchema = {
    properties: {
        room_number: {
            type: 'string',
            maxLength: 10,
            minLength: 1,
            title: 'Room Number'
        },
        floor: {
            type: 'integer',
            maximum: 20,
            minimum: 1,
            title: 'Floor'
        },
        room_type: {
            '$ref': '#/components/schemas/RoomType'
        },
        price_per_night: {
            type: 'number',
            maximum: 100000,
            exclusiveMinimum: 0,
            title: 'Price Per Night'
        },
        status: {
            '$ref': '#/components/schemas/RoomStatus',
            default: 'available'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        room_photo_paths: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Room Photo Paths'
        }
    },
    type: 'object',
    required: ['room_number', 'floor', 'room_type', 'price_per_night'],
    title: 'RoomCreate'
} as const;

export const RoomPublicSchema = {
    properties: {
        room_number: {
            type: 'string',
            maxLength: 10,
            minLength: 1,
            title: 'Room Number'
        },
        floor: {
            type: 'integer',
            maximum: 20,
            minimum: 1,
            title: 'Floor'
        },
        room_type: {
            '$ref': '#/components/schemas/RoomType'
        },
        price_per_night: {
            type: 'number',
            maximum: 100000,
            exclusiveMinimum: 0,
            title: 'Price Per Night'
        },
        status: {
            '$ref': '#/components/schemas/RoomStatus',
            default: 'available'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        room_photo_paths: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Room Photo Paths'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['room_number', 'floor', 'room_type', 'price_per_night', 'id', 'created_at'],
    title: 'RoomPublic'
} as const;

export const RoomStatusSchema = {
    type: 'string',
    enum: ['available', 'occupied', 'cleaning', 'maintenance'],
    title: 'RoomStatus'
} as const;

export const RoomTypeSchema = {
    type: 'string',
    enum: ['standard', 'vip'],
    title: 'RoomType'
} as const;

export const RoomUpdateSchema = {
    properties: {
        room_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Room Number'
        },
        floor: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Floor'
        },
        room_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/RoomType'
                },
                {
                    type: 'null'
                }
            ]
        },
        price_per_night: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price Per Night'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/RoomStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        room_photo_paths: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Room Photo Paths'
        }
    },
    type: 'object',
    title: 'RoomUpdate'
} as const;

export const RoomsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RoomPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RoomsPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 3,
            title: 'Username'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'host'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 3,
            title: 'Username'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'host'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['username', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        username: {
            type: 'string',
            maxLength: 50,
            minLength: 3,
            title: 'Username'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'UserRegister'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: ['admin', 'manager', 'host'],
    title: 'UserRole'
} as const;

export const UserUpdateSchema = {
    properties: {
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        role: {
            '$ref': '#/components/schemas/UserRole',
            default: 'host'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        username: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50,
                    minLength: 3
                },
                {
                    type: 'null'
                }
            ],
            title: 'Username'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;