// This file is auto-generated by @hey-api/openapi-ts

export type AuditLogPublic = {
    id: string;
    user_id: (string | null);
    username: string;
    action: string;
    entity_type: string;
    entity_id: string;
    entity_name: string;
    description: string;
    old_values: ({
    [key: string]: unknown;
} | null);
    new_values: ({
    [key: string]: unknown;
} | null);
    timestamp: string;
};

export type AuditLogsPublic = {
    data: Array<AuditLogPublic>;
    count: number;
};

export type Body_files_upload_passport = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BookingCreate = {
    customer_id: string;
    room_id: string;
    check_in: string;
    check_out: string;
    status?: BookingStatus;
    total_amount: number;
    discount?: number;
    discount_reason?: (string | null);
    payment_method?: PaymentMethod;
    registration_need?: boolean;
};

export type BookingPublic = {
    customer_id: string;
    room_id: string;
    check_in: string;
    check_out: string;
    status?: BookingStatus;
    total_amount: number;
    discount?: number;
    discount_reason?: (string | null);
    payment_method?: PaymentMethod;
    registration_need?: boolean;
    id: string;
    customer?: (CustomerPublic | null);
    room?: (RoomPublic | null);
    booking_date: string;
    created_at: string;
    actual_check_in?: (string | null);
    actual_check_out?: (string | null);
    payment_adjustments?: Array<{
        [key: string]: unknown;
    }>;
};

export type BookingsPublic = {
    data: Array<BookingPublic>;
    count: number;
};

export type BookingStatus = 'confirmed' | 'checked_in' | 'checked_out' | 'cancelled';

export type BookingUpdate = {
    customer_id?: (string | null);
    room_id?: (string | null);
    check_in?: (string | null);
    check_out?: (string | null);
    status?: (BookingStatus | null);
    total_amount?: (number | null);
    discount?: (number | null);
    discount_reason?: (string | null);
    payment_method?: (PaymentMethod | null);
    registration_need?: (boolean | null);
    actual_check_in?: (string | null);
    actual_check_out?: (string | null);
    payment_adjustments?: (Array<{
    [key: string]: unknown;
}> | null);
};

export type CustomerCreate = {
    first_name: string;
    last_name: string;
    phone?: (string | null);
    date_of_birth?: (string | null);
    district?: (District | null);
    passport_photo_path?: (string | null);
    notes?: (string | null);
};

export type CustomerPublic = {
    first_name: string;
    last_name: string;
    phone?: (string | null);
    date_of_birth?: (string | null);
    district?: (District | null);
    passport_photo_path?: (string | null);
    notes?: (string | null);
    id: string;
    total_spent: number;
    total_bookings: number;
    first_booking_date: (string | null);
    last_booking_date: (string | null);
    created_at: string;
};

export type CustomersPublic = {
    data: Array<CustomerPublic>;
    count: number;
};

export type CustomerUpdate = {
    first_name?: (string | null);
    last_name?: (string | null);
    phone?: (string | null);
    date_of_birth?: (string | null);
    district?: (District | null);
    passport_photo_path?: (string | null);
    tags?: (Array<(string)> | null);
    notes?: (string | null);
};

/**
 * Request model for modifying booking dates.
 */
export type DateModificationRequest = {
    new_check_in?: (string | null);
    new_check_out?: (string | null);
};

/**
 * Request model for modifying booking discount with payment adjustment.
 */
export type DiscountModificationRequest = {
    new_discount: number;
    discount_reason?: (string | null);
};

/**
 * Districts of Tashkent - stored as uppercase in DB
 */
export type District = 'ALMAZAR' | 'BEKTEMIR' | 'MIRABAD' | 'MIRZO_ULUGBEK' | 'SERGELI' | 'UCHTEPA' | 'CHILANZAR' | 'SHAYKHANTAKHUR' | 'YUNUSABAD' | 'YAKKASARAY' | 'YASHNABAD' | 'YANGIHAYOT';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

/**
 * Response model for operations that result in payment adjustments.
 */
export type PaymentAdjustmentResponse = {
    booking: BookingPublic;
    payment_difference: number;
};

export type PaymentMethod = 'cash' | 'transfer' | 'terminal';

/**
 * Request model for changing booking room.
 */
export type RoomChangeRequest = {
    new_room_id: string;
};

export type RoomCreate = {
    room_number: string;
    floor: number;
    room_type: RoomType;
    price_per_night: number;
    status?: RoomStatus;
    description?: (string | null);
    room_photo_paths?: Array<(string)>;
};

export type RoomPublic = {
    room_number: string;
    floor: number;
    room_type: RoomType;
    price_per_night: number;
    status?: RoomStatus;
    description?: (string | null);
    room_photo_paths?: Array<(string)>;
    id: string;
    created_at: string;
};

export type RoomsPublic = {
    data: Array<RoomPublic>;
    count: number;
};

export type RoomStatus = 'available' | 'occupied' | 'cleaning' | 'maintenance';

export type RoomType = 'standard' | 'vip';

export type RoomUpdate = {
    room_number?: (string | null);
    floor?: (number | null);
    room_type?: (RoomType | null);
    price_per_night?: (number | null);
    status?: (RoomStatus | null);
    description?: (string | null);
    room_photo_paths?: (Array<(string)> | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    username: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    password: string;
};

export type UserPublic = {
    username: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    id: string;
};

export type UserRegister = {
    username: string;
    password: string;
    full_name?: (string | null);
};

export type UserRole = 'admin' | 'manager' | 'host';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    username?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    username?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginLoginAccessTokenData = {
    body: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginLoginAccessTokenError = (HTTPValidationError);

export type LoginTestTokenResponse = (UserPublic);

export type LoginTestTokenError = unknown;

export type UsersReadUsersData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersReadUsersError = (HTTPValidationError);

export type UsersCreateUserData = {
    body: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersCreateUserError = (HTTPValidationError);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersReadUserMeError = unknown;

export type UsersDeleteUserMeResponse = (Message);

export type UsersDeleteUserMeError = unknown;

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdateUserMeError = (HTTPValidationError);

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersUpdatePasswordMeError = (HTTPValidationError);

export type UsersRegisterUserData = {
    body: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersRegisterUserError = (HTTPValidationError);

export type UsersReadUserByIdData = {
    path: {
        user_id: string;
    };
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersReadUserByIdError = (HTTPValidationError);

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        user_id: string;
    };
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersUpdateUserError = (HTTPValidationError);

export type UsersDeleteUserData = {
    path: {
        user_id: string;
    };
};

export type UsersDeleteUserResponse = (Message);

export type UsersDeleteUserError = (HTTPValidationError);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsHealthCheckError = unknown;

export type UtilsTriggerErrorResponse = (unknown);

export type UtilsTriggerErrorError = unknown;

export type RoomsReadRoomsData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type RoomsReadRoomsResponse = (RoomsPublic);

export type RoomsReadRoomsError = (HTTPValidationError);

export type RoomsCreateRoomData = {
    body: RoomCreate;
};

export type RoomsCreateRoomResponse = (RoomPublic);

export type RoomsCreateRoomError = (HTTPValidationError);

export type RoomsReadRoomData = {
    path: {
        room_id: string;
    };
};

export type RoomsReadRoomResponse = (RoomPublic);

export type RoomsReadRoomError = (HTTPValidationError);

export type RoomsUpdateRoomData = {
    body: RoomUpdate;
    path: {
        room_id: string;
    };
};

export type RoomsUpdateRoomResponse = (RoomPublic);

export type RoomsUpdateRoomError = (HTTPValidationError);

export type RoomsDeleteRoomData = {
    path: {
        room_id: string;
    };
};

export type RoomsDeleteRoomResponse = (Message);

export type RoomsDeleteRoomError = (HTTPValidationError);

export type RoomsReadAvailableRoomsData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type RoomsReadAvailableRoomsResponse = (RoomsPublic);

export type RoomsReadAvailableRoomsError = (HTTPValidationError);

export type RoomsUpdateRoomStatusData = {
    path: {
        room_id: string;
    };
    query: {
        status: RoomStatus;
    };
};

export type RoomsUpdateRoomStatusResponse = (RoomPublic);

export type RoomsUpdateRoomStatusError = (HTTPValidationError);

export type CustomersReadCustomersData = {
    query?: {
        limit?: number;
        search?: (string | null);
        skip?: number;
    };
};

export type CustomersReadCustomersResponse = (CustomersPublic);

export type CustomersReadCustomersError = (HTTPValidationError);

export type CustomersCreateCustomerData = {
    body: CustomerCreate;
};

export type CustomersCreateCustomerResponse = (CustomerPublic);

export type CustomersCreateCustomerError = (HTTPValidationError);

export type CustomersReadCustomerData = {
    path: {
        customer_id: string;
    };
};

export type CustomersReadCustomerResponse = (CustomerPublic);

export type CustomersReadCustomerError = (HTTPValidationError);

export type CustomersUpdateCustomerData = {
    body: CustomerUpdate;
    path: {
        customer_id: string;
    };
};

export type CustomersUpdateCustomerResponse = (CustomerPublic);

export type CustomersUpdateCustomerError = (HTTPValidationError);

export type CustomersDeleteCustomerData = {
    path: {
        customer_id: string;
    };
};

export type CustomersDeleteCustomerResponse = (Message);

export type CustomersDeleteCustomerError = (HTTPValidationError);

export type BookingsReadBookingsData = {
    query?: {
        customer_id?: (string | null);
        date_from?: (string | null);
        date_to?: (string | null);
        limit?: number;
        room_id?: (string | null);
        skip?: number;
        status?: (BookingStatus | null);
    };
};

export type BookingsReadBookingsResponse = (BookingsPublic);

export type BookingsReadBookingsError = (HTTPValidationError);

export type BookingsCreateBookingData = {
    body: BookingCreate;
};

export type BookingsCreateBookingResponse = (BookingPublic);

export type BookingsCreateBookingError = (HTTPValidationError);

export type BookingsReadBookingData = {
    path: {
        booking_id: string;
    };
};

export type BookingsReadBookingResponse = (BookingPublic);

export type BookingsReadBookingError = (HTTPValidationError);

export type BookingsUpdateBookingData = {
    body: BookingUpdate;
    path: {
        booking_id: string;
    };
};

export type BookingsUpdateBookingResponse = (BookingPublic);

export type BookingsUpdateBookingError = (HTTPValidationError);

export type BookingsDeleteBookingData = {
    path: {
        booking_id: string;
    };
};

export type BookingsDeleteBookingResponse = (Message);

export type BookingsDeleteBookingError = (HTTPValidationError);

export type BookingsModifyBookingDatesData = {
    body: DateModificationRequest;
    path: {
        booking_id: string;
    };
};

export type BookingsModifyBookingDatesResponse = (PaymentAdjustmentResponse);

export type BookingsModifyBookingDatesError = (HTTPValidationError);

export type BookingsModifyBookingDiscountData = {
    body: DiscountModificationRequest;
    path: {
        booking_id: string;
    };
};

export type BookingsModifyBookingDiscountResponse = (PaymentAdjustmentResponse);

export type BookingsModifyBookingDiscountError = (HTTPValidationError);

export type BookingsChangeBookingRoomData = {
    body: RoomChangeRequest;
    path: {
        booking_id: string;
    };
};

export type BookingsChangeBookingRoomResponse = (PaymentAdjustmentResponse);

export type BookingsChangeBookingRoomError = (HTTPValidationError);

export type BookingsCheckInBookingData = {
    path: {
        booking_id: string;
    };
};

export type BookingsCheckInBookingResponse = (BookingPublic);

export type BookingsCheckInBookingError = (HTTPValidationError);

export type BookingsCheckOutBookingData = {
    path: {
        booking_id: string;
    };
};

export type BookingsCheckOutBookingResponse = (BookingPublic);

export type BookingsCheckOutBookingError = (HTTPValidationError);

export type BookingsActualCheckInData = {
    path: {
        booking_id: string;
    };
};

export type BookingsActualCheckInResponse = (BookingPublic);

export type BookingsActualCheckInError = (HTTPValidationError);

export type BookingsActualCheckOutData = {
    path: {
        booking_id: string;
    };
};

export type BookingsActualCheckOutResponse = (BookingPublic);

export type BookingsActualCheckOutError = (HTTPValidationError);

export type AuditReadAuditLogsData = {
    query?: {
        action?: (string | null);
        entity_type?: (string | null);
        limit?: number;
        search?: (string | null);
        skip?: number;
        user_name?: (string | null);
    };
};

export type AuditReadAuditLogsResponse = (AuditLogsPublic);

export type AuditReadAuditLogsError = (HTTPValidationError);

export type AuditReadAuditLogData = {
    path: {
        audit_log_id: string;
    };
};

export type AuditReadAuditLogResponse = (AuditLogPublic);

export type AuditReadAuditLogError = (HTTPValidationError);

export type AuditGetAuditStatsResponse = (unknown);

export type AuditGetAuditStatsError = unknown;

export type FilesUploadPassportData = {
    body: Body_files_upload_passport;
};

export type FilesUploadPassportResponse = (unknown);

export type FilesUploadPassportError = (HTTPValidationError);

export type FilesGetFileData = {
    path: {
        file_type: string;
        filename: string;
    };
};

export type FilesGetFileResponse = (unknown);

export type FilesGetFileError = (HTTPValidationError);

export type FilesDeleteFileData = {
    path: {
        file_type: string;
        filename: string;
    };
};

export type FilesDeleteFileResponse = (unknown);

export type FilesDeleteFileError = (HTTPValidationError);