// This file is auto-generated by @hey-api/openapi-ts

/**
 * Request model for exporting analytics.
 */
export type AnalyticsExportRequest = {
    filters: AnalyticsFilter;
    format?: string;
    /**
     * Include charts in export
     */
    include_charts?: boolean;
    /**
     * Which metric sections to include
     */
    metrics_to_include?: Array<(string)>;
};

/**
 * Filter parameters for analytics queries.
 */
export type AnalyticsFilter = {
    date_from: string;
    date_to: string;
    room_id?: (string | null);
    category_id?: (string | null);
    customer_id?: (string | null);
    country_code?: (string | null);
    region?: (string | null);
    district?: (string | null);
    customer_type?: (CustomerType | null);
    tags?: (Array<(string)> | null);
    group_by?: (GroupBy | null);
    /**
     * Include cancelled bookings in metrics
     */
    include_cancelled?: boolean;
};

/**
 * Standard response wrapper for analytics endpoints.
 */
export type AnalyticsResponse = {
    success?: boolean;
    data: unknown;
    generated_at?: string;
    filters_applied?: (AnalyticsFilter | null);
};

export type AuditLogPublic = {
    id: string;
    user_id: (string | null);
    username: string;
    action: string;
    entity_type: string;
    entity_id: string;
    entity_name: string;
    description: string;
    old_values: ({
    [key: string]: unknown;
} | null);
    new_values: ({
    [key: string]: unknown;
} | null);
    timestamp: string;
};

export type AuditLogsPublic = {
    data: Array<AuditLogPublic>;
    count: number;
};

export type Body_files_upload_passport = {
    file: (Blob | File);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type BookingCreate = {
    customer_id: string;
    room_id: string;
    check_in: string;
    check_out: string;
    status?: BookingStatus;
    total_amount: number;
    discount?: number;
    discount_reason?: (string | null);
    payment_method?: PaymentMethod;
    registration_need?: boolean;
};

/**
 * Schema for creating a booking guest.
 */
export type BookingGuestCreate = {
    customer_id?: (string | null);
    first_name?: (string | null);
    last_name?: (string | null);
    passport_photo_path: string;
    country_code?: (string | null);
    region?: (string | null);
    district?: (District | null);
    phone?: (string | null);
    is_primary?: boolean;
};

/**
 * Public schema for booking guest (API responses).
 */
export type BookingGuestPublic = {
    /**
     * Reference to customer if saved to database
     */
    customer_id?: (string | null);
    first_name?: (string | null);
    last_name?: (string | null);
    /**
     * Path to passport photo (required for all guests)
     */
    passport_photo_path: string;
    /**
     * ISO-3166 alpha-2 code (e.g., UZ)
     */
    country_code?: (string | null);
    region?: (string | null);
    district?: (District | null);
    phone?: (string | null);
    /**
     * True if this is the primary guest (booking holder)
     */
    is_primary?: boolean;
    id: string;
    booking_id: string;
    added_at: string;
    customer_name?: (string | null);
};

/**
 * List of booking guests.
 */
export type BookingGuestsPublic = {
    data: Array<BookingGuestPublic>;
    count: number;
};

/**
 * Schema for updating a booking guest.
 */
export type BookingGuestUpdate = {
    first_name?: (string | null);
    last_name?: (string | null);
    passport_photo_path?: (string | null);
    country_code?: (string | null);
    region?: (string | null);
    district?: (District | null);
    phone?: (string | null);
};

/**
 * Public booking schema for API responses.
 *
 * Note: refund_amount and additional_payment are computed properties
 * available on the Booking table model but not serialized in API responses.
 * Calculate these on frontend if needed from payment_adjustments.
 */
export type BookingPublic = {
    customer_id: string;
    room_id: string;
    check_in: string;
    check_out: string;
    status?: BookingStatus;
    total_amount: number;
    discount?: number;
    discount_reason?: (string | null);
    payment_method?: PaymentMethod;
    registration_need?: boolean;
    id: string;
    customer?: (CustomerPublic | null);
    room?: (RoomPublic | null);
    booking_date: string;
    created_at: string;
    actual_check_in?: (string | null);
    actual_check_out?: (string | null);
    payment_adjustments?: Array<{
        [key: string]: unknown;
    }>;
    /**
     * List of guests in this booking
     */
    guests?: Array<BookingGuestPublic>;
};

export type BookingsPublic = {
    data: Array<BookingPublic>;
    count: number;
};

export type BookingStatus = 'confirmed' | 'checked_in' | 'checked_out' | 'cancelled';

export type BookingUpdate = {
    customer_id?: (string | null);
    room_id?: (string | null);
    check_in?: (string | null);
    check_out?: (string | null);
    status?: (BookingStatus | null);
    total_amount?: (number | null);
    discount?: (number | null);
    discount_reason?: (string | null);
    payment_method?: (PaymentMethod | null);
    registration_need?: (boolean | null);
    actual_check_in?: (string | null);
    actual_check_out?: (string | null);
    payment_adjustments?: (Array<{
    [key: string]: unknown;
}> | null);
};

export type BotUserPublic = {
    /**
     * Normalized phone (digits only)
     */
    phone: string;
    /**
     * User first name
     */
    name: string;
    /**
     * Interface language code (ru, uz, en, zh)
     */
    language?: string;
    /**
     * Whether user is active
     */
    is_active?: boolean;
    id: string;
    created_at: string;
    updated_at: string;
};

export type BotUsersPublic = {
    data: Array<BotUserPublic>;
    count: number;
};

/**
 * Update bot user
 */
export type BotUserUpdate = {
    phone?: (string | null);
    name?: (string | null);
    language?: (string | null);
    is_active?: (boolean | null);
};

/**
 * Bot user with generated context for AI
 */
export type BotUserWithContext = {
    user: BotUserPublic;
    context: {
        [key: string]: unknown;
    };
};

/**
 * Schema for creating new campaigns
 */
export type CampaignCreate = {
    name: string;
    type: CampaignType;
    status?: CampaignStatus;
    message_template: string;
    /**
     * JSON criteria for customer selection
     */
    criteria?: {
        [key: string]: unknown;
    };
    /**
     * For trigger campaigns: check frequency in minutes
     */
    trigger_frequency_minutes?: (number | null);
};

/**
 * Request model for executing one-time campaigns
 */
export type CampaignExecutionRequest = {
    /**
     * Execute in test mode (mock SMS)
     */
    test_mode?: boolean;
};

/**
 * Response model for campaign execution
 */
export type CampaignExecutionResponse = {
    campaign_id: string;
    execution_type: string;
    customers_matched: number;
    sms_sent: number;
    sms_failed: number;
    test_mode?: boolean;
    execution_summary?: {
        [key: string]: unknown;
    };
};

/**
 * Public campaign schema for API responses
 */
export type CampaignPublic = {
    name: string;
    type: CampaignType;
    status?: CampaignStatus;
    message_template: string;
    /**
     * JSON criteria for customer selection
     */
    criteria?: {
        [key: string]: unknown;
    };
    /**
     * For trigger campaigns: check frequency in minutes
     */
    trigger_frequency_minutes?: (number | null);
    id: string;
    created_at: string;
    updated_at: string;
    last_executed_at?: (string | null);
    total_sent?: number;
    total_delivered?: number;
    total_failed?: number;
};

/**
 * Collection wrapper for campaigns list API
 */
export type CampaignsPublic = {
    data: Array<CampaignPublic>;
    count: number;
};

/**
 * Campaign lifecycle status
 */
export type CampaignStatus = 'draft' | 'active' | 'paused' | 'completed' | 'archived';

/**
 * Campaign execution types
 */
export type CampaignType = 'onetime' | 'trigger';

/**
 * Schema for updating campaigns - all fields optional
 */
export type CampaignUpdate = {
    name?: (string | null);
    type?: (CampaignType | null);
    status?: (CampaignStatus | null);
    message_template?: (string | null);
    criteria?: ({
    [key: string]: unknown;
} | null);
    trigger_frequency_minutes?: (number | null);
};

export type CustomerCreate = {
    first_name: string;
    last_name: string;
    phone?: (string | null);
    name_cyrillic?: (string | null);
    date_of_birth?: (string | null);
    /**
     * ISO-3166 alpha-2 code (e.g., UZ)
     */
    country_code?: (string | null);
    region?: (string | null);
    district?: (District | null);
    passport_photo_path?: (string | null);
    notes?: (string | null);
    source?: (CustomerSource | null);
};

/**
 * Customer ID lookup response
 */
export type CustomerIdResponse = {
    customer_id: (string | null);
    found: boolean;
};

export type CustomerInquiriesPublic = {
    data: Array<CustomerInquiryPublic>;
    count: number;
};

export type CustomerInquiryCreate = {
    bot_user_id: string;
    customer_id?: (string | null);
    inquiry_type: InquiryType;
    message: string;
    status?: InquiryStatus;
    inquiry_date: string;
    related_booking_date?: (string | null);
};

export type CustomerInquiryPublic = {
    /**
     * Bot user who created inquiry
     */
    bot_user_id: string;
    /**
     * Linked CRM customer (if found by phone)
     */
    customer_id?: (string | null);
    /**
     * Type of inquiry
     */
    inquiry_type: InquiryType;
    /**
     * Inquiry message text
     */
    message: string;
    /**
     * Processing status
     */
    status?: InquiryStatus;
    /**
     * Date when inquiry was made
     */
    inquiry_date: string;
    /**
     * Date of booking being discussed
     */
    related_booking_date?: (string | null);
    /**
     * When inquiry was resolved
     */
    resolved_at?: (string | null);
    /**
     * Notes about resolution
     */
    resolution_notes?: (string | null);
    id: string;
    created_at: string;
    updated_at: string;
    bot_user_name?: (string | null);
    bot_user_phone?: (string | null);
    telegram_username?: (string | null);
    telegram_first_name?: (string | null);
    customer_name?: (string | null);
    customer_phone?: (string | null);
    has_customer?: boolean;
};

export type CustomerInquiryUpdate = {
    status?: (InquiryStatus | null);
    resolved_at?: (string | null);
    resolution_notes?: (string | null);
};

/**
 * Response model for campaign recipient preview
 */
export type CustomerPreviewResponse = {
    campaign_id: string;
    total_matching_customers: number;
    preview_customers: Array<{
        [key: string]: unknown;
    }>;
    criteria_applied: {
        [key: string]: unknown;
    };
};

export type CustomerPublic = {
    first_name: string;
    last_name: string;
    phone?: (string | null);
    name_cyrillic?: (string | null);
    date_of_birth?: (string | null);
    /**
     * ISO-3166 alpha-2 code (e.g., UZ)
     */
    country_code?: (string | null);
    region?: (string | null);
    district?: (District | null);
    passport_photo_path?: (string | null);
    notes?: (string | null);
    source?: (CustomerSource | null);
    id: string;
    total_spent: number;
    total_bookings: number;
    first_booking_date: (string | null);
    last_booking_date: (string | null);
    created_at: string;
    tags: Array<(string)>;
};

/**
 * Customer acquisition sources
 */
export type CustomerSource = 'WALK_IN' | 'INSTAGRAM' | 'OLX';

export type CustomersPublic = {
    data: Array<CustomerPublic>;
    count: number;
};

/**
 * Customer type categories for filtering.
 */
export type CustomerType = 'new' | 'returning';

export type CustomerUpdate = {
    first_name?: (string | null);
    last_name?: (string | null);
    name_cyrillic?: (string | null);
    phone?: (string | null);
    date_of_birth?: (string | null);
    country_code?: (string | null);
    region?: (string | null);
    district?: (District | null);
    passport_photo_path?: (string | null);
    tags?: (Array<(string)> | null);
    notes?: (string | null);
    source?: (CustomerSource | null);
};

/**
 * Request model for modifying booking dates.
 */
export type DateModificationRequest = {
    new_check_in?: (string | null);
    new_check_out?: (string | null);
};

/**
 * Request model for modifying booking discount with payment adjustment.
 */
export type DiscountModificationRequest = {
    new_discount: number;
    discount_reason?: (string | null);
};

/**
 * Districts of Tashkent - stored as uppercase in DB
 */
export type District = 'ALMAZAR' | 'BEKTEMIR' | 'MIRABAD' | 'MIRZO_ULUGBEK' | 'SERGELI' | 'UCHTEPA' | 'CHILANZAR' | 'SHAYKHANTAKHUR' | 'YUNUSABAD' | 'YAKKASARAY' | 'YASHNABAD' | 'YANGIHAYOT';

export type ExpenseCategoriesPublic = {
    data: Array<ExpenseCategoryPublic>;
    count: number;
};

export type ExpenseCategoryCreate = {
    name: string;
    description?: (string | null);
};

export type ExpenseCategoryPublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at: string;
};

export type ExpenseCategoryUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type ExpenseCreate = {
    category_id: string;
    /**
     * Expense amount (must be positive)
     */
    amount: number;
    description?: (string | null);
    /**
     * Date when expense occurred
     */
    expense_date?: string;
};

export type ExpensePublic = {
    category_id: string;
    /**
     * Expense amount (must be positive)
     */
    amount: number;
    description?: (string | null);
    /**
     * Date when expense occurred
     */
    expense_date?: string;
    id: string;
    created_at: string;
    updated_at: string;
    category: ExpenseCategoryPublic;
};

export type ExpensesPublic = {
    data: Array<ExpensePublic>;
    count: number;
};

export type ExpenseUpdate = {
    category_id?: (string | null);
    amount?: (number | null);
    description?: (string | null);
    expense_date?: (string | null);
};

/**
 * Grouping options for analytics.
 */
export type GroupBy = 'day' | 'week' | 'month' | 'room' | 'payment_method' | 'country' | 'region' | 'district' | 'age_group';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Status of inquiry processing.
 */
export type InquiryStatus = 'new' | 'in_progress' | 'resolved' | 'closed';

/**
 * Type of customer inquiry.
 */
export type InquiryType = 'complaint' | 'suggestion' | 'question';

export type Message = {
    message: string;
};

/**
 * Response model for operations that result in payment adjustments.
 */
export type PaymentAdjustmentResponse = {
    booking: BookingPublic;
    payment_difference: number;
};

export type PaymentMethod = 'cash' | 'transfer' | 'terminal';

/**
 * Request body for resolving inquiry
 */
export type ResolveInquiryRequest = {
    resolution_notes: string;
};

export type RoomCategoriesPublic = {
    data: Array<RoomCategoryPublic>;
    count: number;
};

export type RoomCategoryCreate = {
    name: string;
    description?: (string | null);
};

export type RoomCategoryPublic = {
    name: string;
    description?: (string | null);
    id: string;
    created_at: string;
};

/**
 * Request model for changing booking room.
 */
export type RoomChangeRequest = {
    new_room_id: string;
};

export type RoomCreate = {
    room_number: string;
    floor: number;
    category_id?: (string | null);
    price_per_night: number;
    /**
     * Maximum number of guests allowed in the room
     */
    max_occupancy?: number;
    status?: RoomStatus;
    description?: (string | null);
    room_photo_paths?: Array<(string)>;
};

export type RoomPublic = {
    room_number: string;
    floor: number;
    category_id?: (string | null);
    price_per_night: number;
    /**
     * Maximum number of guests allowed in the room
     */
    max_occupancy?: number;
    status?: RoomStatus;
    description?: (string | null);
    room_photo_paths?: Array<(string)>;
    id: string;
    created_at: string;
    category?: (RoomCategoryPublic | null);
};

export type RoomsPublic = {
    data: Array<RoomPublic>;
    count: number;
};

export type RoomStatus = 'available' | 'occupied' | 'cleaning' | 'maintenance';

export type RoomUpdate = {
    room_number?: (string | null);
    floor?: (number | null);
    category_id?: (string | null);
    price_per_night?: (number | null);
    max_occupancy?: (number | null);
    status?: (RoomStatus | null);
    description?: (string | null);
    room_photo_paths?: (Array<(string)> | null);
};

/**
 * Request to create session (login)
 */
export type SessionCreateRequest = {
    telegram_id: number;
    phone: string;
    name: string;
    language?: string;
    telegram_username?: (string | null);
    telegram_first_name: string;
    telegram_last_name?: (string | null);
    telegram_language_code?: (string | null);
};

/**
 * Collection wrapper for SMS history
 */
export type SMSHistoryList = {
    data: Array<SMSHistoryPublic>;
    count: number;
};

/**
 * Public SMS history schema
 */
export type SMSHistoryPublic = {
    id: string;
    campaign_id: string;
    customer_id: string;
    message: string;
    status: SMSStatus;
    sent_at: string;
    delivered_at?: (string | null);
    customer_phone?: (string | null);
    customer_name?: (string | null);
    error_message?: (string | null);
};

/**
 * SMS delivery status
 */
export type SMSStatus = 'pending' | 'sent' | 'delivered' | 'failed' | 'mock';

/**
 * Public schema for system settings.
 */
export type SystemSettingsPublic = {
    /**
     * System default language
     */
    language?: string;
    /**
     * System default currency
     */
    currency?: string;
    id: string;
    updated_at: string;
};

/**
 * Schema for updating system settings.
 */
export type SystemSettingsUpdate = {
    language?: (string | null);
    currency?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Response model for trigger campaign checks
 */
export type TriggerCheckResponse = {
    campaigns_checked: number;
    campaigns_executed: number;
    total_sms_sent: number;
    execution_details?: Array<{
        [key: string]: unknown;
    }>;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    username: string;
    password: string;
    is_active?: boolean;
    full_name?: (string | null);
    role?: UserRole;
};

export type UserPublic = {
    username: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: UserRole;
    language?: string;
    currency?: string;
    id: string;
};

export type UserRegister = {
    username: string;
    password: string;
    full_name?: (string | null);
};

export type UserRole = 'admin' | 'manager' | 'host';

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    username?: (string | null);
    password?: (string | null);
    is_active?: (boolean | null);
    full_name?: (string | null);
    role?: (UserRole | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    username?: (string | null);
    language?: (string | null);
    currency?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type LoginLoginAccessTokenData = {
    body: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginLoginAccessTokenError = (HTTPValidationError);

export type LoginTestTokenResponse = (UserPublic);

export type LoginTestTokenError = unknown;

export type UsersReadUsersData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersReadUsersError = (HTTPValidationError);

export type UsersCreateUserData = {
    body: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersCreateUserError = (HTTPValidationError);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersReadUserMeError = unknown;

export type UsersDeleteUserMeResponse = (Message);

export type UsersDeleteUserMeError = unknown;

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdateUserMeError = (HTTPValidationError);

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersUpdatePasswordMeError = (HTTPValidationError);

export type UsersRegisterUserData = {
    body: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersRegisterUserError = (HTTPValidationError);

export type UsersReadUserByIdData = {
    path: {
        user_id: string;
    };
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersReadUserByIdError = (HTTPValidationError);

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        user_id: string;
    };
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersUpdateUserError = (HTTPValidationError);

export type UsersDeleteUserData = {
    path: {
        user_id: string;
    };
};

export type UsersDeleteUserResponse = (Message);

export type UsersDeleteUserError = (HTTPValidationError);

export type UtilsHealthCheckResponse = (boolean);

export type UtilsHealthCheckError = unknown;

export type UtilsTriggerErrorResponse = (unknown);

export type UtilsTriggerErrorError = unknown;

export type RoomsReadRoomsData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type RoomsReadRoomsResponse = (RoomsPublic);

export type RoomsReadRoomsError = (HTTPValidationError);

export type RoomsCreateRoomData = {
    body: RoomCreate;
};

export type RoomsCreateRoomResponse = (RoomPublic);

export type RoomsCreateRoomError = (HTTPValidationError);

export type RoomsReadRoomData = {
    path: {
        room_id: string;
    };
};

export type RoomsReadRoomResponse = (RoomPublic);

export type RoomsReadRoomError = (HTTPValidationError);

export type RoomsUpdateRoomData = {
    body: RoomUpdate;
    path: {
        room_id: string;
    };
};

export type RoomsUpdateRoomResponse = (RoomPublic);

export type RoomsUpdateRoomError = (HTTPValidationError);

export type RoomsDeleteRoomData = {
    path: {
        room_id: string;
    };
};

export type RoomsDeleteRoomResponse = (Message);

export type RoomsDeleteRoomError = (HTTPValidationError);

export type RoomsReadAvailableRoomsData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type RoomsReadAvailableRoomsResponse = (RoomsPublic);

export type RoomsReadAvailableRoomsError = (HTTPValidationError);

export type RoomsReadRoomCategoriesData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type RoomsReadRoomCategoriesResponse = (RoomCategoriesPublic);

export type RoomsReadRoomCategoriesError = (HTTPValidationError);

export type RoomsCreateRoomCategoryData = {
    body: RoomCategoryCreate;
};

export type RoomsCreateRoomCategoryResponse = (RoomCategoryPublic);

export type RoomsCreateRoomCategoryError = (HTTPValidationError);

export type RoomsDeleteRoomCategoryData = {
    path: {
        category_id: string;
    };
};

export type RoomsDeleteRoomCategoryResponse = (Message);

export type RoomsDeleteRoomCategoryError = (HTTPValidationError);

export type RoomsUpdateRoomStatusData = {
    path: {
        room_id: string;
    };
    query: {
        status: RoomStatus;
    };
};

export type RoomsUpdateRoomStatusResponse = (RoomPublic);

export type RoomsUpdateRoomStatusError = (HTTPValidationError);

export type CustomersReadCustomersData = {
    query?: {
        country_code?: (string | null);
        date_from?: (string | null);
        date_to?: (string | null);
        district?: (string | null);
        limit?: number;
        max_bookings?: (number | null);
        max_spent?: (number | null);
        min_bookings?: (number | null);
        min_spent?: (number | null);
        order_by?: string;
        order_direction?: string;
        region?: (string | null);
        search?: (string | null);
        skip?: number;
    };
};

export type CustomersReadCustomersResponse = (CustomersPublic);

export type CustomersReadCustomersError = (HTTPValidationError);

export type CustomersCreateCustomerData = {
    body: CustomerCreate;
};

export type CustomersCreateCustomerResponse = (CustomerPublic);

export type CustomersCreateCustomerError = (HTTPValidationError);

export type CustomersReadCustomerData = {
    path: {
        customer_id: string;
    };
};

export type CustomersReadCustomerResponse = (CustomerPublic);

export type CustomersReadCustomerError = (HTTPValidationError);

export type CustomersUpdateCustomerData = {
    body: CustomerUpdate;
    path: {
        customer_id: string;
    };
};

export type CustomersUpdateCustomerResponse = (CustomerPublic);

export type CustomersUpdateCustomerError = (HTTPValidationError);

export type CustomersDeleteCustomerData = {
    path: {
        customer_id: string;
    };
};

export type CustomersDeleteCustomerResponse = (Message);

export type CustomersDeleteCustomerError = (HTTPValidationError);

export type BookingsReadBookingsData = {
    query?: {
        customer_id?: (string | null);
        date_from?: (string | null);
        date_to?: (string | null);
        limit?: number;
        room_id?: (string | null);
        skip?: number;
        status?: (BookingStatus | null);
    };
};

export type BookingsReadBookingsResponse = (BookingsPublic);

export type BookingsReadBookingsError = (HTTPValidationError);

export type BookingsCreateBookingData = {
    body: BookingCreate;
};

export type BookingsCreateBookingResponse = (BookingPublic);

export type BookingsCreateBookingError = (HTTPValidationError);

export type BookingsReadBookingData = {
    path: {
        booking_id: string;
    };
};

export type BookingsReadBookingResponse = (BookingPublic);

export type BookingsReadBookingError = (HTTPValidationError);

export type BookingsUpdateBookingData = {
    body: BookingUpdate;
    path: {
        booking_id: string;
    };
};

export type BookingsUpdateBookingResponse = (BookingPublic);

export type BookingsUpdateBookingError = (HTTPValidationError);

export type BookingsDeleteBookingData = {
    path: {
        booking_id: string;
    };
};

export type BookingsDeleteBookingResponse = (Message);

export type BookingsDeleteBookingError = (HTTPValidationError);

export type BookingsModifyBookingDatesData = {
    body: DateModificationRequest;
    path: {
        booking_id: string;
    };
};

export type BookingsModifyBookingDatesResponse = (PaymentAdjustmentResponse);

export type BookingsModifyBookingDatesError = (HTTPValidationError);

export type BookingsModifyBookingDiscountData = {
    body: DiscountModificationRequest;
    path: {
        booking_id: string;
    };
};

export type BookingsModifyBookingDiscountResponse = (PaymentAdjustmentResponse);

export type BookingsModifyBookingDiscountError = (HTTPValidationError);

export type BookingsChangeBookingRoomData = {
    body: RoomChangeRequest;
    path: {
        booking_id: string;
    };
};

export type BookingsChangeBookingRoomResponse = (PaymentAdjustmentResponse);

export type BookingsChangeBookingRoomError = (HTTPValidationError);

export type BookingsCheckInBookingData = {
    path: {
        booking_id: string;
    };
};

export type BookingsCheckInBookingResponse = (BookingPublic);

export type BookingsCheckInBookingError = (HTTPValidationError);

export type BookingsCheckOutBookingData = {
    path: {
        booking_id: string;
    };
};

export type BookingsCheckOutBookingResponse = (BookingPublic);

export type BookingsCheckOutBookingError = (HTTPValidationError);

export type BookingsActualCheckInData = {
    path: {
        booking_id: string;
    };
};

export type BookingsActualCheckInResponse = (BookingPublic);

export type BookingsActualCheckInError = (HTTPValidationError);

export type BookingsActualCheckOutData = {
    path: {
        booking_id: string;
    };
};

export type BookingsActualCheckOutResponse = (BookingPublic);

export type BookingsActualCheckOutError = (HTTPValidationError);

export type BookingGuestsGetBookingGuestsData = {
    path: {
        booking_id: string;
    };
};

export type BookingGuestsGetBookingGuestsResponse = (BookingGuestsPublic);

export type BookingGuestsGetBookingGuestsError = (HTTPValidationError);

export type BookingGuestsAddGuestToBookingData = {
    body: BookingGuestCreate;
    path: {
        booking_id: string;
    };
};

export type BookingGuestsAddGuestToBookingResponse = (BookingGuestPublic);

export type BookingGuestsAddGuestToBookingError = (HTTPValidationError);

export type BookingGuestsUpdateBookingGuestData = {
    body: BookingGuestUpdate;
    path: {
        booking_id: string;
        guest_id: string;
    };
};

export type BookingGuestsUpdateBookingGuestResponse = (BookingGuestPublic);

export type BookingGuestsUpdateBookingGuestError = (HTTPValidationError);

export type BookingGuestsRemoveGuestFromBookingData = {
    path: {
        booking_id: string;
        guest_id: string;
    };
};

export type BookingGuestsRemoveGuestFromBookingResponse = (Message);

export type BookingGuestsRemoveGuestFromBookingError = (HTTPValidationError);

export type CampaignsReadCampaignsData = {
    query?: {
        campaign_type?: (CampaignType | null);
        limit?: number;
        search?: (string | null);
        skip?: number;
        status?: (CampaignStatus | null);
    };
};

export type CampaignsReadCampaignsResponse = (CampaignsPublic);

export type CampaignsReadCampaignsError = (HTTPValidationError);

export type CampaignsCreateCampaignData = {
    body: CampaignCreate;
};

export type CampaignsCreateCampaignResponse = (CampaignPublic);

export type CampaignsCreateCampaignError = (HTTPValidationError);

export type CampaignsReadCampaignData = {
    path: {
        campaign_id: string;
    };
};

export type CampaignsReadCampaignResponse = (CampaignPublic);

export type CampaignsReadCampaignError = (HTTPValidationError);

export type CampaignsUpdateCampaignData = {
    body: CampaignUpdate;
    path: {
        campaign_id: string;
    };
};

export type CampaignsUpdateCampaignResponse = (CampaignPublic);

export type CampaignsUpdateCampaignError = (HTTPValidationError);

export type CampaignsDeleteCampaignData = {
    path: {
        campaign_id: string;
    };
};

export type CampaignsDeleteCampaignResponse = (Message);

export type CampaignsDeleteCampaignError = (HTTPValidationError);

export type CampaignsExecuteCampaignData = {
    body: CampaignExecutionRequest;
    path: {
        campaign_id: string;
    };
};

export type CampaignsExecuteCampaignResponse = (CampaignExecutionResponse);

export type CampaignsExecuteCampaignError = (HTTPValidationError);

export type CampaignsPreviewCampaignRecipientsData = {
    path: {
        campaign_id: string;
    };
};

export type CampaignsPreviewCampaignRecipientsResponse = (CustomerPreviewResponse);

export type CampaignsPreviewCampaignRecipientsError = (HTTPValidationError);

export type CampaignsCheckTriggersResponse = (TriggerCheckResponse);

export type CampaignsCheckTriggersError = unknown;

export type CampaignsGetCampaignSmsHistoryData = {
    path: {
        campaign_id: string;
    };
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type CampaignsGetCampaignSmsHistoryResponse = (SMSHistoryList);

export type CampaignsGetCampaignSmsHistoryError = (HTTPValidationError);

export type AuditReadAuditLogsData = {
    query?: {
        action?: (string | null);
        entity_type?: (string | null);
        limit?: number;
        search?: (string | null);
        skip?: number;
        user_name?: (string | null);
    };
};

export type AuditReadAuditLogsResponse = (AuditLogsPublic);

export type AuditReadAuditLogsError = (HTTPValidationError);

export type AuditReadAuditLogData = {
    path: {
        audit_log_id: string;
    };
};

export type AuditReadAuditLogResponse = (AuditLogPublic);

export type AuditReadAuditLogError = (HTTPValidationError);

export type AuditGetAuditStatsResponse = (unknown);

export type AuditGetAuditStatsError = unknown;

export type FilesUploadPassportData = {
    body: Body_files_upload_passport;
};

export type FilesUploadPassportResponse = (unknown);

export type FilesUploadPassportError = (HTTPValidationError);

export type FilesGetFileData = {
    path: {
        file_type: string;
        filename: string;
    };
};

export type FilesGetFileResponse = (unknown);

export type FilesGetFileError = (HTTPValidationError);

export type FilesDeleteFileData = {
    path: {
        file_type: string;
        filename: string;
    };
};

export type FilesDeleteFileResponse = (unknown);

export type FilesDeleteFileError = (HTTPValidationError);

export type BotLoginSessionData = {
    body: SessionCreateRequest;
};

export type BotLoginSessionResponse = (BotUserPublic);

export type BotLoginSessionError = (HTTPValidationError);

export type BotListBotUsersData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type BotListBotUsersResponse = (BotUsersPublic);

export type BotListBotUsersError = (HTTPValidationError);

export type BotGetSessionData = {
    path: {
        telegram_id: number;
    };
};

export type BotGetSessionResponse = (BotUserPublic);

export type BotGetSessionError = (HTTPValidationError);

export type BotUpdateSessionUserData = {
    body: BotUserUpdate;
    path: {
        telegram_id: number;
    };
};

export type BotUpdateSessionUserResponse = (BotUserPublic);

export type BotUpdateSessionUserError = (HTTPValidationError);

export type BotLogoutSessionData = {
    path: {
        telegram_id: number;
    };
};

export type BotLogoutSessionResponse = (unknown);

export type BotLogoutSessionError = (HTTPValidationError);

export type BotGetUserWithContextData = {
    path: {
        telegram_id: number;
    };
};

export type BotGetUserWithContextResponse = (BotUserWithContext);

export type BotGetUserWithContextError = (HTTPValidationError);

export type BotGetCustomerIdByTelegramData = {
    path: {
        telegram_id: number;
    };
};

export type BotGetCustomerIdByTelegramResponse = (CustomerIdResponse);

export type BotGetCustomerIdByTelegramError = (HTTPValidationError);

export type BotCreateInquiryData = {
    body: CustomerInquiryCreate;
};

export type BotCreateInquiryResponse = (CustomerInquiryPublic);

export type BotCreateInquiryError = (HTTPValidationError);

export type AnalyticsGetDashboardMetricsData = {
    query: {
        /**
         * Filter by room category id
         */
        category_id?: (string | null);
        /**
         * ISO-2 country code
         */
        country_code?: (string | null);
        /**
         * Customer type: new/returning
         */
        customer_type?: (CustomerType | null);
        /**
         * Start date for the analysis period
         */
        date_from: string;
        /**
         * End date for the analysis period
         */
        date_to: string;
        /**
         * District code (Tashkent only)
         */
        district?: (string | null);
        /**
         * Include cancelled bookings
         */
        include_cancelled?: boolean;
        /**
         * Region/oblast code
         */
        region?: (string | null);
        /**
         * Filter by specific room id or 'all'
         */
        room_id?: (string | null);
        /**
         * Customer tags (any-of)
         */
        tags?: (Array<(string)> | null);
    };
};

export type AnalyticsGetDashboardMetricsResponse = (AnalyticsResponse);

export type AnalyticsGetDashboardMetricsError = (HTTPValidationError);

export type AnalyticsGetHourlyDistributionData = {
    query: {
        /**
         * Filter by room category id
         */
        category_id?: (string | null);
        country_code?: (string | null);
        customer_type?: (CustomerType | null);
        date_from: string;
        date_to: string;
        district?: (string | null);
        metric?: string;
        region?: (string | null);
        room_id?: (string | null);
        tags?: (Array<(string)> | null);
    };
};

export type AnalyticsGetHourlyDistributionResponse = (AnalyticsResponse);

export type AnalyticsGetHourlyDistributionError = (HTTPValidationError);

export type AnalyticsGetSeasonalTrendsData = {
    query?: {
        room_id?: (string | null);
        years?: number;
    };
};

export type AnalyticsGetSeasonalTrendsResponse = (AnalyticsResponse);

export type AnalyticsGetSeasonalTrendsError = (HTTPValidationError);

export type AnalyticsGetTopCustomersData = {
    query?: {
        date_from?: (string | null);
        date_to?: (string | null);
        limit?: number;
        room_id?: (string | null);
    };
};

export type AnalyticsGetTopCustomersResponse = (unknown);

export type AnalyticsGetTopCustomersError = (HTTPValidationError);

export type AnalyticsGetRevenueDetailsData = {
    query: {
        /**
         * Filter by room category id
         */
        category_id?: (string | null);
        date_from: string;
        date_to: string;
        group_by?: string;
        include_cancelled?: boolean;
        room_id?: (string | null);
    };
};

export type AnalyticsGetRevenueDetailsResponse = (AnalyticsResponse);

export type AnalyticsGetRevenueDetailsError = (HTTPValidationError);

export type AnalyticsGetOccupancyDetailsData = {
    query: {
        /**
         * Filter by room category id
         */
        category_id?: (string | null);
        date_from: string;
        date_to: string;
        room_id?: (string | null);
    };
};

export type AnalyticsGetOccupancyDetailsResponse = (AnalyticsResponse);

export type AnalyticsGetOccupancyDetailsError = (HTTPValidationError);

export type AnalyticsGetCustomerDetailsData = {
    query: {
        /**
         * Filter by room category id
         */
        category_id?: (string | null);
        country_code?: (string | null);
        customer_type?: (CustomerType | null);
        date_from: string;
        date_to: string;
        district?: (string | null);
        region?: (string | null);
        room_id?: (string | null);
        tags?: (Array<(string)> | null);
    };
};

export type AnalyticsGetCustomerDetailsResponse = (AnalyticsResponse);

export type AnalyticsGetCustomerDetailsError = (HTTPValidationError);

export type AnalyticsGetQuickStatsResponse = (AnalyticsResponse);

export type AnalyticsGetQuickStatsError = unknown;

export type AnalyticsGetGeoRevenueData = {
    query: {
        date_from: string;
        date_to: string;
        level?: string;
    };
};

export type AnalyticsGetGeoRevenueResponse = (unknown);

export type AnalyticsGetGeoRevenueError = (HTTPValidationError);

export type AnalyticsExportPdfData = {
    body: AnalyticsExportRequest;
};

export type AnalyticsExportPdfResponse = (unknown);

export type AnalyticsExportPdfError = (HTTPValidationError);

export type AnalyticsExportExcelData = {
    body: AnalyticsExportRequest;
};

export type AnalyticsExportExcelResponse = (unknown);

export type AnalyticsExportExcelError = (HTTPValidationError);

export type ExpensesReadExpenseCategoriesData = {
    query?: {
        limit?: number;
        skip?: number;
    };
};

export type ExpensesReadExpenseCategoriesResponse = (ExpenseCategoriesPublic);

export type ExpensesReadExpenseCategoriesError = (HTTPValidationError);

export type ExpensesCreateExpenseCategoryData = {
    body: ExpenseCategoryCreate;
};

export type ExpensesCreateExpenseCategoryResponse = (ExpenseCategoryPublic);

export type ExpensesCreateExpenseCategoryError = (HTTPValidationError);

export type ExpensesReadExpenseCategoryData = {
    path: {
        category_id: string;
    };
};

export type ExpensesReadExpenseCategoryResponse = (ExpenseCategoryPublic);

export type ExpensesReadExpenseCategoryError = (HTTPValidationError);

export type ExpensesUpdateExpenseCategoryData = {
    body: ExpenseCategoryUpdate;
    path: {
        category_id: string;
    };
};

export type ExpensesUpdateExpenseCategoryResponse = (ExpenseCategoryPublic);

export type ExpensesUpdateExpenseCategoryError = (HTTPValidationError);

export type ExpensesDeleteExpenseCategoryData = {
    path: {
        category_id: string;
    };
};

export type ExpensesDeleteExpenseCategoryResponse = (Message);

export type ExpensesDeleteExpenseCategoryError = (HTTPValidationError);

export type ExpensesReadExpensesData = {
    query?: {
        category_id?: (string | null);
        limit?: number;
        skip?: number;
    };
};

export type ExpensesReadExpensesResponse = (ExpensesPublic);

export type ExpensesReadExpensesError = (HTTPValidationError);

export type ExpensesCreateExpenseData = {
    body: ExpenseCreate;
};

export type ExpensesCreateExpenseResponse = (ExpensePublic);

export type ExpensesCreateExpenseError = (HTTPValidationError);

export type ExpensesReadExpenseData = {
    path: {
        expense_id: string;
    };
};

export type ExpensesReadExpenseResponse = (ExpensePublic);

export type ExpensesReadExpenseError = (HTTPValidationError);

export type ExpensesUpdateExpenseData = {
    body: ExpenseUpdate;
    path: {
        expense_id: string;
    };
};

export type ExpensesUpdateExpenseResponse = (ExpensePublic);

export type ExpensesUpdateExpenseError = (HTTPValidationError);

export type ExpensesDeleteExpenseData = {
    path: {
        expense_id: string;
    };
};

export type ExpensesDeleteExpenseResponse = (Message);

export type ExpensesDeleteExpenseError = (HTTPValidationError);

export type GeoGetCountriesResponse = (Array<{
    [key: string]: (string);
}>);

export type GeoGetCountriesError = unknown;

export type GeoGetRegionsData = {
    query: {
        country: string;
    };
};

export type GeoGetRegionsResponse = (Array<{
    [key: string]: (string);
}>);

export type GeoGetRegionsError = (HTTPValidationError);

export type GeoGetDistrictsData = {
    query: {
        region: string;
    };
};

export type GeoGetDistrictsResponse = (Array<{
    [key: string]: (string);
}>);

export type GeoGetDistrictsError = (HTTPValidationError);

export type InquiriesReadInquiriesData = {
    query?: {
        customer_id?: (string | null);
        customers_only?: (boolean | null);
        limit?: number;
        skip?: number;
        status?: (InquiryStatus | null);
    };
};

export type InquiriesReadInquiriesResponse = (CustomerInquiriesPublic);

export type InquiriesReadInquiriesError = (HTTPValidationError);

export type InquiriesCreateInquiryApiData = {
    body: CustomerInquiryCreate;
};

export type InquiriesCreateInquiryApiResponse = (CustomerInquiryPublic);

export type InquiriesCreateInquiryApiError = (HTTPValidationError);

export type InquiriesReadInquiryData = {
    path: {
        inquiry_id: string;
    };
};

export type InquiriesReadInquiryResponse = (CustomerInquiryPublic);

export type InquiriesReadInquiryError = (HTTPValidationError);

export type InquiriesUpdateInquiryData = {
    body: CustomerInquiryUpdate;
    path: {
        inquiry_id: string;
    };
};

export type InquiriesUpdateInquiryResponse = (CustomerInquiryPublic);

export type InquiriesUpdateInquiryError = (HTTPValidationError);

export type InquiriesResolveInquiryData = {
    body: ResolveInquiryRequest;
    path: {
        inquiry_id: string;
    };
};

export type InquiriesResolveInquiryResponse = (CustomerInquiryPublic);

export type InquiriesResolveInquiryError = (HTTPValidationError);

export type SystemSettingsGetSystemSettingsResponse = (SystemSettingsPublic);

export type SystemSettingsGetSystemSettingsError = unknown;

export type SystemSettingsUpdateSystemSettingsData = {
    body: SystemSettingsUpdate;
};

export type SystemSettingsUpdateSystemSettingsResponse = (SystemSettingsPublic);

export type SystemSettingsUpdateSystemSettingsError = (HTTPValidationError);