"""refactor bot auth: remove telegram_id from bot_users, add bot_sessions table

Revision ID: 0996b0e04581
Revises: ed521f73651b
Create Date: 2025-10-15 14:00:32.922294

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0996b0e04581'
down_revision = 'ed521f73651b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_sessions',
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('bot_user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bot_user_id'], ['bot_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_sessions_bot_user_id'), 'bot_sessions', ['bot_user_id'], unique=False)
    op.create_index(op.f('ix_bot_sessions_telegram_id'), 'bot_sessions', ['telegram_id'], unique=True)
    op.drop_index('ix_bot_users_telegram_id', table_name='bot_users')
    op.drop_column('bot_users', 'telegram_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_users', sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_index('ix_bot_users_telegram_id', 'bot_users', ['telegram_id'], unique=True)
    op.drop_index(op.f('ix_bot_sessions_telegram_id'), table_name='bot_sessions')
    op.drop_index(op.f('ix_bot_sessions_bot_user_id'), table_name='bot_sessions')
    op.drop_table('bot_sessions')
    # ### end Alembic commands ###
