"""Add bot_users and customer_inquiries tables

Revision ID: 0d7ce46cf090
Revises: af443c54f6a2
Create Date: 2025-10-14 17:19:44.923433

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0d7ce46cf090'
down_revision = 'af443c54f6a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_users',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('surname', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('birthdate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('business_type', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_users_phone'), 'bot_users', ['phone'], unique=True)
    op.create_index(op.f('ix_bot_users_telegram_id'), 'bot_users', ['telegram_id'], unique=True)
    op.create_table('customer_inquiries',
    sa.Column('bot_user_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('booking_id', sa.Uuid(), nullable=True),
    sa.Column('inquiry_type', sa.Enum('COMPLAINT', 'SUGGESTION', 'QUESTION', name='inquirytype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='inquirystatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='inquirypriority'), nullable=False),
    sa.Column('inquiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('related_booking_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['bot_user_id'], ['bot_users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_inquiries_booking_id'), 'customer_inquiries', ['booking_id'], unique=False)
    op.create_index(op.f('ix_customer_inquiries_bot_user_id'), 'customer_inquiries', ['bot_user_id'], unique=False)
    op.create_index(op.f('ix_customer_inquiries_customer_id'), 'customer_inquiries', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_inquiries_status'), 'customer_inquiries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_inquiries_status'), table_name='customer_inquiries')
    op.drop_index(op.f('ix_customer_inquiries_customer_id'), table_name='customer_inquiries')
    op.drop_index(op.f('ix_customer_inquiries_bot_user_id'), table_name='customer_inquiries')
    op.drop_index(op.f('ix_customer_inquiries_booking_id'), table_name='customer_inquiries')
    op.drop_table('customer_inquiries')
    op.drop_index(op.f('ix_bot_users_telegram_id'), table_name='bot_users')
    op.drop_index(op.f('ix_bot_users_phone'), table_name='bot_users')
    op.drop_table('bot_users')
    # ### end Alembic commands ###
