"""Add RoomCategory and link to Room

Revision ID: 19a105ab0912
Revises: 3a1c2b7d9f10
Create Date: 2025-10-06 18:55:02.253825

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '19a105ab0912'
down_revision = '3a1c2b7d9f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roomcategory',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roomcategory_name'), 'roomcategory', ['name'], unique=True)
    op.drop_index('ix_customer_country_code', table_name='customer')
    op.drop_index('ix_customer_region', table_name='customer')
    op.add_column('room', sa.Column('category_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_room_category_id'), 'room', ['category_id'], unique=False)
    op.create_foreign_key(None, 'room', 'roomcategory', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room', type_='foreignkey')
    op.drop_index(op.f('ix_room_category_id'), table_name='room')
    op.drop_column('room', 'category_id')
    op.create_index('ix_customer_region', 'customer', ['region'], unique=False)
    op.create_index('ix_customer_country_code', 'customer', ['country_code'], unique=False)
    op.drop_index(op.f('ix_roomcategory_name'), table_name='roomcategory')
    op.drop_table('roomcategory')
    # ### end Alembic commands ###
