"""Remove legacy refund_amount and additional_payment fields, add payment_adjustments JSON field

Revision ID: 322cf8b5d6e3
Revises: a6086dd7375f
Create Date: 2025-09-20 14:14:17.079656

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '322cf8b5d6e3'
down_revision = 'a6086dd7375f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('payment_adjustments', sa.JSON(), nullable=True))
    op.drop_column('booking', 'additional_payment')
    op.drop_column('booking', 'refund_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('refund_amount', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.add_column('booking', sa.Column('additional_payment', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.drop_column('booking', 'payment_adjustments')
    # ### end Alembic commands ###
