"""Add version field for optimistic locking

Revision ID: 32b326b6343d
Revises: a5a3a5a1380c
Create Date: 2025-09-14 11:48:53.204760

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '32b326b6343d'
down_revision = 'a5a3a5a1380c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    op.add_column('booking', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('room', sa.Column('version', sa.Integer(), nullable=True))

    # Set default value for existing rows
    op.execute('UPDATE booking SET version = 0 WHERE version IS NULL')
    op.execute('UPDATE customer SET version = 0 WHERE version IS NULL')
    op.execute('UPDATE room SET version = 0 WHERE version IS NULL')

    # Make columns non-nullable
    op.alter_column('booking', 'version', nullable=False)
    op.alter_column('customer', 'version', nullable=False)
    op.alter_column('room', 'version', nullable=False)

    # Create indexes
    op.create_index(op.f('ix_booking_version'), 'booking', ['version'], unique=False)
    op.create_index(op.f('ix_customer_version'), 'customer', ['version'], unique=False)
    op.create_index(op.f('ix_room_version'), 'room', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_version'), table_name='room')
    op.drop_column('room', 'version')
    op.drop_index(op.f('ix_customer_version'), table_name='customer')
    op.drop_column('customer', 'version')
    op.drop_index(op.f('ix_booking_version'), table_name='booking')
    op.drop_column('booking', 'version')
    # ### end Alembic commands ###
