"""initial schema

Revision ID: 405b3106cee7
Revises: 
Create Date: 2025-10-21 22:29:14.864178

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '405b3106cee7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_users',
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_users_phone'), 'bot_users', ['phone'], unique=True)
    op.create_table('campaign',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('type', sa.Enum('ONETIME', 'TRIGGER', name='campaigntype'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='campaignstatus'), nullable=False),
    sa.Column('message_template', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('trigger_frequency_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_sent', sa.Integer(), nullable=False),
    sa.Column('total_delivered', sa.Integer(), nullable=False),
    sa.Column('total_failed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_name'), 'campaign', ['name'], unique=False)
    op.create_index(op.f('ix_campaign_status'), 'campaign', ['status'], unique=False)
    op.create_index(op.f('ix_campaign_type'), 'campaign', ['type'], unique=False)
    op.create_table('customer',
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('name_cyrillic', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('district', sa.Enum('ALMAZAR', 'BEKTEMIR', 'MIRABAD', 'MIRZO_ULUGBEK', 'SERGELI', 'UCHTEPA', 'CHILANZAR', 'SHAYKHANTAKHUR', 'YUNUSABAD', 'YAKKASARAY', 'YASHNABAD', 'YANGIHAYOT', name='district'), nullable=True),
    sa.Column('passport_photo_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('total_spent', sa.Float(), nullable=False),
    sa.Column('total_bookings', sa.Integer(), nullable=False),
    sa.Column('first_booking_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_booking_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_phone'), 'customer', ['phone'], unique=True)
    op.create_table('expensecategory',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expensecategory_name'), 'expensecategory', ['name'], unique=True)
    op.create_table('roomcategory',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roomcategory_name'), 'roomcategory', ['name'], unique=True)
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'HOST', name='userrole'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('auditlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('entity_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditlog_action'), 'auditlog', ['action'], unique=False)
    op.create_index(op.f('ix_auditlog_entity_type'), 'auditlog', ['entity_type'], unique=False)
    op.create_index(op.f('ix_auditlog_timestamp'), 'auditlog', ['timestamp'], unique=False)
    op.create_index(op.f('ix_auditlog_user_id'), 'auditlog', ['user_id'], unique=False)
    op.create_table('bot_sessions',
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('bot_user_id', sa.Uuid(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('language_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bot_user_id'], ['bot_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_sessions_bot_user_id'), 'bot_sessions', ['bot_user_id'], unique=False)
    op.create_index(op.f('ix_bot_sessions_telegram_id'), 'bot_sessions', ['telegram_id'], unique=True)
    op.create_table('customer_inquiries',
    sa.Column('bot_user_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('inquiry_type', sa.Enum('COMPLAINT', 'SUGGESTION', 'QUESTION', name='inquirytype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='inquirystatus'), nullable=False),
    sa.Column('inquiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('related_booking_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bot_user_id'], ['bot_users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_inquiries_bot_user_id'), 'customer_inquiries', ['bot_user_id'], unique=False)
    op.create_index(op.f('ix_customer_inquiries_customer_id'), 'customer_inquiries', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_inquiries_status'), 'customer_inquiries', ['status'], unique=False)
    op.create_table('expense',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('expense_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['expensecategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('room_number', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('price_per_night', sa.Float(), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'OCCUPIED', 'CLEANING', 'MAINTENANCE', name='roomstatus'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('room_photo_paths', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['roomcategory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_category_id'), 'room', ['category_id'], unique=False)
    op.create_index(op.f('ix_room_room_number'), 'room', ['room_number'], unique=True)
    op.create_table('smshistory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'MOCK', name='smsstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('customer_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('provider_message_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('provider_status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('error_code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('user_sms_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smshistory_campaign_id'), 'smshistory', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_smshistory_customer_id'), 'smshistory', ['customer_id'], unique=False)
    op.create_index(op.f('ix_smshistory_provider'), 'smshistory', ['provider'], unique=False)
    op.create_index(op.f('ix_smshistory_provider_message_id'), 'smshistory', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_smshistory_status'), 'smshistory', ['status'], unique=False)
    op.create_index(op.f('ix_smshistory_user_sms_id'), 'smshistory', ['user_sms_id'], unique=False)
    op.create_table('booking',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=False),
    sa.Column('discount_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('payment_method', sa.Enum('CASH', 'TRANSFER', 'TERMINAL', name='paymentmethod'), nullable=False),
    sa.Column('registration_need', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_adjustments', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_customer_id'), 'booking', ['customer_id'], unique=False)
    op.create_index(op.f('ix_booking_room_id'), 'booking', ['room_id'], unique=False)
    op.create_index(op.f('ix_booking_status'), 'booking', ['status'], unique=False)
    op.create_table('booking_guests',
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('passport_photo_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('district', sa.Enum('ALMAZAR', 'BEKTEMIR', 'MIRABAD', 'MIRZO_ULUGBEK', 'SERGELI', 'UCHTEPA', 'CHILANZAR', 'SHAYKHANTAKHUR', 'YUNUSABAD', 'YAKKASARAY', 'YASHNABAD', 'YANGIHAYOT', name='district'), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_guests_booking_id'), 'booking_guests', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_guests_booking_id'), table_name='booking_guests')
    op.drop_table('booking_guests')
    op.drop_index(op.f('ix_booking_status'), table_name='booking')
    op.drop_index(op.f('ix_booking_room_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_customer_id'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix_smshistory_user_sms_id'), table_name='smshistory')
    op.drop_index(op.f('ix_smshistory_status'), table_name='smshistory')
    op.drop_index(op.f('ix_smshistory_provider_message_id'), table_name='smshistory')
    op.drop_index(op.f('ix_smshistory_provider'), table_name='smshistory')
    op.drop_index(op.f('ix_smshistory_customer_id'), table_name='smshistory')
    op.drop_index(op.f('ix_smshistory_campaign_id'), table_name='smshistory')
    op.drop_table('smshistory')
    op.drop_index(op.f('ix_room_room_number'), table_name='room')
    op.drop_index(op.f('ix_room_category_id'), table_name='room')
    op.drop_table('room')
    op.drop_table('expense')
    op.drop_index(op.f('ix_customer_inquiries_status'), table_name='customer_inquiries')
    op.drop_index(op.f('ix_customer_inquiries_customer_id'), table_name='customer_inquiries')
    op.drop_index(op.f('ix_customer_inquiries_bot_user_id'), table_name='customer_inquiries')
    op.drop_table('customer_inquiries')
    op.drop_index(op.f('ix_bot_sessions_telegram_id'), table_name='bot_sessions')
    op.drop_index(op.f('ix_bot_sessions_bot_user_id'), table_name='bot_sessions')
    op.drop_table('bot_sessions')
    op.drop_index(op.f('ix_auditlog_user_id'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_timestamp'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_entity_type'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_action'), table_name='auditlog')
    op.drop_table('auditlog')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_roomcategory_name'), table_name='roomcategory')
    op.drop_table('roomcategory')
    op.drop_index(op.f('ix_expensecategory_name'), table_name='expensecategory')
    op.drop_table('expensecategory')
    op.drop_index(op.f('ix_customer_phone'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_campaign_type'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_status'), table_name='campaign')
    op.drop_index(op.f('ix_campaign_name'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_index(op.f('ix_bot_users_phone'), table_name='bot_users')
    op.drop_table('bot_users')
    # ### end Alembic commands ###
