"""Add CASCADE delete to audit log user_id foreign key

Revision ID: 49040ae2f9b4
Revises: 9d76550042ef
Create Date: 2025-09-08 11:59:51.800656

"""
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op

# revision identifiers, used by Alembic.
revision = '49040ae2f9b4'
down_revision = '9d76550042ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auditlog', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_auditlog_action'), 'auditlog', ['action'], unique=False)
    op.create_index(op.f('ix_auditlog_entity_type'), 'auditlog', ['entity_type'], unique=False)
    op.create_index(op.f('ix_auditlog_timestamp'), 'auditlog', ['timestamp'], unique=False)
    op.create_index(op.f('ix_auditlog_user_id'), 'auditlog', ['user_id'], unique=False)
    op.drop_constraint('auditlog_user_id_fkey', 'auditlog', type_='foreignkey')
    op.create_foreign_key(None, 'auditlog', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('customer_phone_key', 'customer', type_='unique')
    op.create_index(op.f('ix_customer_phone'), 'customer', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_phone'), table_name='customer')
    op.create_unique_constraint('customer_phone_key', 'customer', ['phone'])
    op.drop_constraint(None, 'auditlog', type_='foreignkey')
    op.create_foreign_key('auditlog_user_id_fkey', 'auditlog', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('ix_auditlog_user_id'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_timestamp'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_entity_type'), table_name='auditlog')
    op.drop_index(op.f('ix_auditlog_action'), table_name='auditlog')
    op.alter_column('auditlog', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
