"""Initial schema

Revision ID: 4d225c547808
Revises: 
Create Date: 2025-10-16 09:17:37.773683

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4d225c547808'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_sessions', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('bot_sessions', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False))
    op.add_column('bot_sessions', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('bot_sessions', sa.Column('language_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.drop_column('bot_users', 'surname')
    op.drop_column('bot_users', 'birthdate')
    op.drop_column('bot_users', 'business_type')
    op.drop_index('ix_customer_inquiries_booking_id', table_name='customer_inquiries')
    op.drop_constraint('customer_inquiries_booking_id_fkey', 'customer_inquiries', type_='foreignkey')
    op.drop_constraint('customer_inquiries_assigned_to_fkey', 'customer_inquiries', type_='foreignkey')
    op.drop_column('customer_inquiries', 'priority')
    op.drop_column('customer_inquiries', 'booking_id')
    op.drop_column('customer_inquiries', 'assigned_to')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_inquiries', sa.Column('assigned_to', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('customer_inquiries', sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('customer_inquiries', sa.Column('priority', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='inquirypriority'), autoincrement=False, nullable=False))
    op.create_foreign_key('customer_inquiries_assigned_to_fkey', 'customer_inquiries', 'user', ['assigned_to'], ['id'])
    op.create_foreign_key('customer_inquiries_booking_id_fkey', 'customer_inquiries', 'booking', ['booking_id'], ['id'])
    op.create_index('ix_customer_inquiries_booking_id', 'customer_inquiries', ['booking_id'], unique=False)
    op.add_column('bot_users', sa.Column('business_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('bot_users', sa.Column('birthdate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('bot_users', sa.Column('surname', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('bot_sessions', 'language_code')
    op.drop_column('bot_sessions', 'last_name')
    op.drop_column('bot_sessions', 'first_name')
    op.drop_column('bot_sessions', 'username')
    # ### end Alembic commands ###
