"""add source field to customer

Revision ID: 5262f825ba66
Revises: 99514be55752
Create Date: 2025-11-01 11:57:28.498687

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5262f825ba66'
down_revision = '99514be55752'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type first
    customersource_enum = sa.Enum('WALK_IN', 'INSTAGRAM', 'OLX', name='customersource')
    customersource_enum.create(op.get_bind(), checkfirst=True)

    # Then add the column
    op.add_column('customer', sa.Column('source', customersource_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the column first
    op.drop_column('customer', 'source')

    # Then drop the ENUM type
    customersource_enum = sa.Enum('WALK_IN', 'INSTAGRAM', 'OLX', name='customersource')
    customersource_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
