"""Drop room.room_type column

Revision ID: 674bac539586
Revises: 19a105ab0912
Create Date: 2025-10-06 19:28:40.798050

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '674bac539586'
down_revision = '19a105ab0912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room', 'room_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('room_type', postgresql.ENUM('STANDARD', 'VIP', name='roomtype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
