"""Add unique constraint to customer phone

Revision ID: 9d76550042ef
Revises: ed773035736b
Create Date: 2025-09-08 15:48:34.019046

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9d76550042ef'
down_revision = 'ed773035736b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customer', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='unique')
    # ### end Alembic commands ###
