"""Add actual dates and payment adjustment fields to booking

Revision ID: a6086dd7375f
Revises: 32b326b6343d
Create Date: 2025-09-19 16:51:19.111543

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a6086dd7375f'
down_revision = '32b326b6343d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('actual_check_in', sa.DateTime(timezone=True), nullable=True))
    op.add_column('booking', sa.Column('actual_check_out', sa.DateTime(timezone=True), nullable=True))

    # Add payment adjustment columns with default values for existing data
    op.add_column('booking', sa.Column('refund_amount', sa.Float(), nullable=True))
    op.add_column('booking', sa.Column('additional_payment', sa.Float(), nullable=True))

    # Set default values for existing records
    op.execute("UPDATE booking SET refund_amount = 0.0 WHERE refund_amount IS NULL")
    op.execute("UPDATE booking SET additional_payment = 0.0 WHERE additional_payment IS NULL")

    # Make columns non-nullable with defaults
    op.alter_column('booking', 'refund_amount', nullable=False, server_default='0.0')
    op.alter_column('booking', 'additional_payment', nullable=False, server_default='0.0')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'additional_payment')
    op.drop_column('booking', 'refund_amount')
    op.drop_column('booking', 'actual_check_out')
    op.drop_column('booking', 'actual_check_in')
    # ### end Alembic commands ###
