"""booking_guests: swap full_name/origin_city/email to first/last + geo

Revision ID: af443c54f6a2
Revises: a1b2c3d4e5f6
Create Date: 2025-10-14 12:22:45.038191

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af443c54f6a2'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_guests', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('booking_guests', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('booking_guests', sa.Column('country_code', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True))
    op.add_column('booking_guests', sa.Column('region', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('booking_guests', sa.Column('district', sa.Enum('ALMAZAR', 'BEKTEMIR', 'MIRABAD', 'MIRZO_ULUGBEK', 'SERGELI', 'UCHTEPA', 'CHILANZAR', 'SHAYKHANTAKHUR', 'YUNUSABAD', 'YAKKASARAY', 'YASHNABAD', 'YANGIHAYOT', name='district'), nullable=True))
    op.alter_column('booking_guests', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index('ix_booking_guests_customer_id', table_name='booking_guests')
    op.drop_column('booking_guests', 'email')
    op.drop_column('booking_guests', 'full_name')
    op.drop_column('booking_guests', 'origin_city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_guests', sa.Column('origin_city', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('booking_guests', sa.Column('full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('booking_guests', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index('ix_booking_guests_customer_id', 'booking_guests', ['customer_id'], unique=False)
    op.alter_column('booking_guests', 'added_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('booking_guests', 'district')
    op.drop_column('booking_guests', 'region')
    op.drop_column('booking_guests', 'country_code')
    op.drop_column('booking_guests', 'last_name')
    op.drop_column('booking_guests', 'first_name')
    # ### end Alembic commands ###
