"""Add ReportJob and ReportHistory tables

Revision ID: cf0d3e73815b
Revises: 49040ae2f9b4
Create Date: 2025-09-09 10:20:13.369916

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'cf0d3e73815b'
down_revision = '49040ae2f9b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reportjob',
    sa.Column('type', sa.Enum('BOOKING_SUMMARY', 'CUSTOMER_REPORT', 'ROOM_OCCUPANCY', 'REVENUE_REPORT', 'AUDIT_LOG_EXPORT', 'FULL_DATA_EXPORT', name='reportjobtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='reportjobstatus'), nullable=False),
    sa.Column('format', sa.Enum('JSON', 'CSV', 'EXCEL', 'PDF', name='reportformat'), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('result_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('result_size', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reportjob_created_at'), 'reportjob', ['created_at'], unique=False)
    op.create_index(op.f('ix_reportjob_user_id'), 'reportjob', ['user_id'], unique=False)
    op.create_table('reporthistory',
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['reportjob.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporthistory_action'), 'reporthistory', ['action'], unique=False)
    op.create_index(op.f('ix_reporthistory_job_id'), 'reporthistory', ['job_id'], unique=False)
    op.create_index(op.f('ix_reporthistory_timestamp'), 'reporthistory', ['timestamp'], unique=False)
    op.create_index(op.f('ix_reporthistory_user_id'), 'reporthistory', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reporthistory_user_id'), table_name='reporthistory')
    op.drop_index(op.f('ix_reporthistory_timestamp'), table_name='reporthistory')
    op.drop_index(op.f('ix_reporthistory_job_id'), table_name='reporthistory')
    op.drop_index(op.f('ix_reporthistory_action'), table_name='reporthistory')
    op.drop_table('reporthistory')
    op.drop_index(op.f('ix_reportjob_user_id'), table_name='reportjob')
    op.drop_index(op.f('ix_reportjob_created_at'), table_name='reportjob')
    op.drop_table('reportjob')
    # ### end Alembic commands ###
